package org.example;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.sql.Date;
import java.util.*;


@RestController	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	@Autowired
	private WarehouseStockRepository warehouseRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {

		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	@PostMapping(path="/addWh")
	public @ResponseBody String addNewWh(
			@RequestParam String productname,
			@RequestParam String whname,
			@RequestParam int warehouseAnzahl,
			@RequestParam int productAnzahl) {

		for (int w = 1; w <= warehouseAnzahl; w++) {

			List<ProductData> products = new LinkedList<>();

			for (int p = 1; p <= productAnzahl; p++) {
				ProductData product = new ProductData(
						String.valueOf(p),
						productname + p,
						"String productCategory",
						1,
						"String productUnit"
				);
				products.add(product);
			}

			WarehouseStock warehouse = new WarehouseStock(

					whname + w,
					"String timestamp",
					"String warehouseCountry",
					"String warehouseCity",
					"String address",
					products
			);

			warehouseRepository.save(warehouse);
		}

		return "Saved";
	}
	@GetMapping("/warehouse/{id}")
	public WarehouseStock getWarehouseData(@PathVariable int id) {
		return warehouseRepository.findByWarehouseId(id);
	}
	@GetMapping("/{warehouseId}/{productId}")
	public @ResponseBody ProductData getSingleProduct(
			@PathVariable Integer warehouseId,
			@PathVariable String productId) {

		WarehouseStock warehouse =
				warehouseRepository.findByWarehouseId(warehouseId);

		if (warehouse == null) {
			return null;
		}

		for (ProductData product : warehouse.productData) {
			if (product.productId.equals(productId)) {
				return product;
			}
		}

		return null;
	}
	@PutMapping("/warehouse/{warehouseId}/name/{newName}")
	public @ResponseBody WarehouseStock updateWarehouseName(
			@PathVariable Integer warehouseId,
			@PathVariable String newName) {

		WarehouseStock existing =
				warehouseRepository.findByWarehouseId(warehouseId);

		if (existing == null) {
			return null;
		}

		existing.warehouseName = newName;

		return warehouseRepository.save(existing);
	}
	@PostMapping("/warehouse/{warehouseId}/purchase/{item}")
	public @ResponseBody WarehouseStock addPurchase(
			@PathVariable Integer warehouseId,
			@PathVariable String item) {


		Einkauf newPurchase = new Einkauf(item);
		WarehouseStock warehouse =
				warehouseRepository.findByWarehouseId(warehouseId);

		if (warehouse == null) {
			return null;
		}
		if (warehouse.purchaseRecords == null) {
			warehouse.purchaseRecords = new ArrayList<>();
		}

		warehouse.purchaseRecords.add(newPurchase);

		return warehouseRepository.save(warehouse);
	}
}
